name: Tests

on:
  pull_request:
  push:

jobs:    
  testing:  
    runs-on: ubuntu-latest
    steps:
    - name: Getting files from GitHub
      uses: actions/checkout@v1
    - name: Configuring Ruby 2.6
      uses: actions/setup-ruby@master
      with:
        ruby-version: 2.6.x
    - name: Checking Ruby version
      run: |
        ruby -v
    - name: setup-chromedriver
      uses: nanasess/setup-chromedriver@v1.0.1
    - name: Test with Rake
      run: |
        sudo apt-get install libsqlite3-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        gem install rspec
        rake test
